import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import ImageCarousel from "./components/ImageCarousel";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <ImageCarousel />

            <main>
                <h1>Welcome to PHD Security</h1>
            </main>

            <footer className={styles.footer}></footer>
        </>
    );
}
